name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag kageja/docker-remote-exp:$(date +%s)
      
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_UNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWD}}
      run: echo ${{secrets.DOCKER_HUB_PASSWD}} | docker login -u ${{secrets.DOCKER_HUB_UNAME}} --password-stdin
      
#     - name: Docker Login
#       uses: docker/login-action@v1.10.0
#       with:
#         # Username used to log against the Docker registry
#         username:  ${{secrets.DOCKER_HUB_UNAME}}
#         # Password or personal access token used to log against the Docker registry
#         password: ${{secrets.DOCKER_HUB_PASSWD}}
      
    - name: Docker Push
      run: docker push kageja/docker-remote-exp
