name: Docker Image CI
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TEST: test
  DOCKER_HUB_USERNAME: ${{ vars.DOCKER_HUB_UNAME }}
  REGISTRYNAME: ${{ vars.REGISTRYNAME }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_HUB_UNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWD }}

    - name: Test Point for docker config after login
      run: |
        echo "See below uncencrypted data =>"
        cat /home/runner/.docker/config.json
  
      # Setting up Docker Buildx with docker-container driver is required
      # at the moment to be able to use a subdirectory with Git context
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and Push Docker All Images
      uses: docker/build-push-action@v5
      with:
        push: true
        context: "{{defaultContext}}"
        file: Dockerfile
        tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.REGISTRYNAME }}:latest
#        docker build --build-arg="JAR_FILE_NAME=docker-java-api-example-0.0.1" . -t "${DOCKER_HUB_USERNAME}/${REGISTRYNAME}" -f ./Dockerfile
